language: bash
before_install:
- openssl aes-256-cbc -K $encrypted_8b31c0736099_key -iv $encrypted_8b31c0736099_iv
  -in cert.pem.enc -out cert.pem -d
script:
- sudo apt-get update
- sudo apt-get install dnsutils --assume-yes
- export packer_host=$(nslookup packer.hackathon.schibsted.io | grep -A10 answer |
  grep Address | cut -d ' ' -f2 | head -1)
- echo $packer_host
- chmod 600 cert.pem
- rsync -a -arvce "ssh -i cert.pem -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  . packer@$packer_host:/tmp/${TRAVIS_BUILD_ID}
- ssh -t -t -i cert.pem -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
  packer@$packer_host "${TRAVIS_BUILD_ID}"
after_success:
- echo "ok"
